version: '3.5'
services:
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_INIT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_INIT_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db

  mongodb-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_ADMIN_USER_NAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_ADMIN_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${DB_URL}
