# Пользователи


## Создать пользователя
POST http://localhost:4000/users HTTP/1.1
Content-Type: application/json

{
  "name": "Test User",
  "email": "testuser@mail.ru",
  "password": "123456qwerty",
  "userType": "pro"
}
###


# Предложения


## Создать предложение
POST http://localhost:4000/offers HTTP/1.1
Content-Type: application/json

{
  "title": "Новое предложение",
  "description": "Новое предложение, созданное запросом из queries.http",
  "publicationDate": "2022-09-14T10:41:43.974Z",
  "city": "Paris",
  "previewPhotoUrl": "preview-photo.jpg",
  "photosUrls": ["photo1.jpg", "photo2.jpg", "photo3.jpg", "photo4.jpg", "photo5.jpg", "photo6.jpg"],
  "isPremium": true,
  "offerType": "house",
  "roomsAmount": 5,
  "guestsLimit": 5,
  "price": 10500,
  "facilities": ["Laptop friendly workspace"],
  "author": "6342eb54978a4d0f1ca76fe3",
  "coordinates": [48.85661, 2.351499]
}
###
## Получить список предложений (дефолтное ограничение выборки)
GET http://localhost:4000/offers/ HTTP/1.1
Content-Type: application/json
###
## Получить список предложений (пользовательское ограничение выборки)
GET http://localhost:4000/offers?size=1 HTTP/1.1
Content-Type: application/json
###
## Получить данные по конкретному предложению
GET http://localhost:4000/offers/6342eb54978a4d0f1ca76fea HTTP/1.1
Content-Type: application/json
###
## Обновить данные по конкретному предложению
PATCH http://localhost:4000/offers/6348f23cef5bbe986157c5e5 HTTP/1.1
Content-Type: application/json

{
  "title": "Новый заголовок",
  "description": "Обновлённое описание",
  "roomsAmount": 6,
  "guestsLimit": 8
}
###
## Удалить предложение
DELETE http://localhost:4000/offers/6349007ad7b3a77e3b9b3289 HTTP/1.1
Content-Type: application/json
###


# Комментарии

## Создание комментария
POST http://localhost:4000/comments/6342eb54978a4d0f1ca76fea HTTP/1.1
Content-Type: application/json

{
  "text":  "Новый комментарий к предложению",
  "publicationDate": "2022-10-14T10:41:43.974Z",
  "rating": 4,
  "author": "6348f8fcef5bbe986157c5ed"
}
###
## Получить комментарии (дефолтное ограничение выборки)
GET http://localhost:4000/comments/6342eb54978a4d0f1ca76fea HTTP/1.1
Content-Type: application/json
###
## Получить комментарии (пользовательское ограничение выборки)
GET http://localhost:4000/comments/6342eb54978a4d0f1ca76fea?size=1 HTTP/1.1
Content-Type: application/json
###
