# Пользователи


## Создать пользователя
POST http://localhost:4000/users HTTP/1.1
Content-Type: application/json

{
  "name": "Стив Джобс",
  "email": "jobs@gmail.ru",
  "password": "12345qwerty",
  "userType": "pro"
}
###
## Авторизация пользователя
POST http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "jobs@gmail.ru",
  "password": "12345qwerty"
}
###
## Проверка токена пользователя
GET http://localhost:4000/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImpvYnNAZ21haWwucnUiLCJpZCI6IjYzNGM0MTczZmVlOTM4ZDgxMzRlOTNmYSIsImlhdCI6MTY2NjQwNjQwNCwiZXhwIjoxNjY2NTc5MjA0fQ.yk0ZmpU5hrlDBi5l868vxAxwx-xTKA344JpTx4XCdVQ
###
## Добавить аватар пользователя

POST http://localhost:4000/users/634c3ea5fee938d8134e93f3/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="author_1266178750.jpeg"
Content-Type: image/png

< /Users/Anton/Desktop/author_1266178750.jpeg
------WebKitFormBoundary7MA4YWxkTrZu0gW--
###


# Предложения


## Создать предложение
POST http://localhost:4000/offers HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImpvYnNAZ21haWwucnUiLCJpZCI6IjYzNGM0MTczZmVlOTM4ZDgxMzRlOTNmYSIsImlhdCI6MTY2NjYwNjYyMSwiZXhwIjoxNjY2Nzc5NDIxfQ.zED8zSGCeRUAuDr4BCulS7h6u_eomsLmndx29vZ9QPw

{
  "title": "Предложение 3",
  "description": "Новое предложение, созданное запросом из queries.http, 3",
  "city": "Paris",
  "previewPhotoUrl": "preview-photo.jpg",
  "photosUrls": ["photo1.jpg", "photo2.jpg", "photo3.jpg", "photo4.jpg", "photo5.jpg", "photo6.jpg"],
  "isPremium": true,
  "offerType": "house",
  "roomsAmount": 5,
  "guestsLimit": 5,
  "price": 10500,
  "facilities": ["Laptop friendly workspace"],
  "author": "634c3e71fee938d8134e93f0",
  "coordinates": [48.85661, 2.351499]
}
###
## Получить список предложений (дефолтное ограничение выборки)
GET http://localhost:4000/offers/ HTTP/1.1
Content-Type: application/json
###
## Получить список предложений (пользовательское ограничение выборки)
GET http://localhost:4000/offers?limit=1 HTTP/1.1
Content-Type: application/json
###
## Получить данные по конкретному предложению
GET http://localhost:4000/offers/634c4181b990d516a1e14522 HTTP/1.1
Content-Type: application/json
###
## Обновить данные по конкретному предложению
PATCH http://localhost:4000/offers/63566930d86a679638ad162e HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImpvYnNAZ21haWwucnUiLCJpZCI6IjYzNGM0MTczZmVlOTM4ZDgxMzRlOTNmYSIsImlhdCI6MTY2NjYwNjYyMSwiZXhwIjoxNjY2Nzc5NDIxfQ.zED8zSGCeRUAuDr4BCulS7h6u_eomsLmndx29vZ9QPw

{
  "title": "Новый заголовок 3",
  "description": "Обновлённое описание 3",
  "roomsAmount": 6,
  "guestsLimit": 8
}
###
## Удалить предложение
DELETE http://localhost:4000/offers/6349007ad7b3a77e3b9b3289 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImpvYnNAZ21haWwucnUiLCJpZCI6IjYzNGM0MTczZmVlOTM4ZDgxMzRlOTNmYSIsImlhdCI6MTY2NjQwNjQwNCwiZXhwIjoxNjY2NTc5MjA0fQ.yk0ZmpU5hrlDBi5l868vxAxwx-xTKA344JpTx4XCdVQ
###


# Комментарии


## Создание комментария
POST http://localhost:4000/comments/634c4181b990d516a1e14522 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImpvYnNAZ21haWwucnUiLCJpZCI6IjYzNGM0MTczZmVlOTM4ZDgxMzRlOTNmYSIsImlhdCI6MTY2NjQwNjQwNCwiZXhwIjoxNjY2NTc5MjA0fQ.yk0ZmpU5hrlDBi5l868vxAxwx-xTKA344JpTx4XCdVQ

{
  "text":  "Комментарий к предложению 2",
  "rating": 3
}
###
## Получить комментарии (дефолтное ограничение выборки)
GET http://localhost:4000/comments/634c4181b990d516a1e14522 HTTP/1.1
Content-Type: application/json
###
## Получить комментарии (пользовательское ограничение выборки)
GET http://localhost:4000/comments/634c4181b990d516a1e14522?limit=1 HTTP/1.1
Content-Type: application/json
###
